#!/bin/sh

### BEGIN INIT INFO
# Provides:          autonmap
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Service to auto-launch nmap.
# Description:       Service to auto-launch nmap and run a series of scans. 
### END INIT INFO

. /lib/lsb/init-functions

# /etc/init.d/autonmap: start and stop the autonmap daemon

# Process' files
# TODO: Accept as args?
PIDFILE='/var/run/autonmap.pid'
BIN='autonmap'
WRAPPER="/opt/autonmap/$BIN"

start() {

  if [ -x $WRAPPER ]; then
    log_daemon_msg "autonmap: Starting autonmap daemon using wrapper script $WRAPPER"
    echo
  else
    log_failure_msg "autonmap: $WRAPPER does not exist or is not executable!"
    exit 1
  fi

  start-stop-daemon --pidfile $PIDFILE -m \
  -b \
  --start -x $WRAPPER

  pgrep $BIN 2>&1 > /dev/null
  if [ $? = 0 ]; then
    log_success_msg "autonmap: started successfully"
    exit 0
  else
    log_failure_msg "autonmap: $WRAPPER appears to have failed to start"
    exit 2
  fi
}

stop() {
  log_daemon_msg "autonmap: Stopping autonmap daemon" "autonmap"

  start-stop-daemon --pidfile $PIDFILE \
  --stop -x $NMAP \
  --signal 9

  rm -f $PIDFILE

  log_success_msg "autonmap: stopped"
  exit 0
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|force-reload)
    stop
    start
    ;;
  status)
    status_of_proc -p $PIDFILE "$WRAPPER" autonmap
    exit $?
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|status}"
    exit 1
esac
exit 0

